const _ = require('lodash')
const debug = require('../../utils/debug')('user:enter-email');
const render = require('../../utils/render');

/**
 * @description Ask user to enter email.
 * This router will display different template files by checking if ctx.session.success exists.
 * 
 * ctx.session could have one of those:
 * {
 *  errors: {
 *    invliadLink: true 
 *  },
 *  success: {
 *    emailSent: true,
 *    pwReset: true
 *  }
 * }
 */
module.exports = async (ctx, next) => {
  /**
   * @type {{emailSent: boolean, pwReset: boolean}}
   */
  const success = ctx.session.success;

  /**
   * This part is enabled only after email is sent or password is reset.
   */
  if (!_.isEmpty(success)) {
    ctx.state.success = success;
    ctx.body = await render('password/success.html', ctx.state);

    delete ctx.session.success;
    return;
  }

  /**
   * @description When used clicked a link that is expired, already used, or not generated by this system.
   * This part is enabled the first time user clicked password reset or clicked an invalid link in his/her email.
   * It is also used for invalid email.
   * @type {boolean}
   */
  const invalidLink = ctx.session.invalidLink;
  if (invalidLink) {
    ctx.state.errors = {
      invalidLink
    };
  }
  
  ctx.body = await render('password/enter-email.html', ctx.state);

  delete ctx.session.invalidLink;
};