const _ = require('lodash')
const debug = require('../../utils/debug')('user:enter-email');
const render = require('../../utils/render');

/**
 * @description Ask user to enter email
 * ctx.session could have one of those:
 * {
 *  errors: {
 *    invliadLink: true 
 *  },
 *  success: {
 *    emailSent: true,
 *    pwReset: true
 *  }
 * }
 */
module.exports = async (ctx, next) => {
  /**
   * @type {{emailSent: boolean, pwReset: boolean}}
   */
  const success = ctx.session.success;

  if (!_.isEmpty(success)) {
    ctx.state.success = success;
    ctx.body = await render('password/success.html', ctx.state);

    delete ctx.session.success;
    return;
  }

  /**
   * @description When used clicked a link that is expires, already used, or not generated by this system.
   * @type {boolean}
   */
  const invalidLink = ctx.session.invalidLink;
  if (invalidLink) {
    ctx.state.errors = {
      invalidLink
    };
  }
  
  ctx.body = await render('password/enter-email.html', ctx.state);

  delete ctx.session.invalidLink;
};